server:
    port: 80
#    ssl:
#        key-store: classpath:server.p12
#        key-store-password: 1540975363258
#        keyStoreType: PKCS12
#        keyAlias: 1

wechat:
    server: https://47.104.8.164:80/


spring:
    datasource:
        url: jdbc:mysql://118.190.202.148:3306/BUPT_IOT?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#        url: jdbc:mysql://localhost:3306/BUPt_IOT?useUnicode=true&characterEncoding=UTF-8
        username: root
#        username: root
        password: Gantch815
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package:  com.edu.bupt.wechatpost.model


